import type { Metadata } from "next";
import "@/style/globals.css";
import ClientProvider from "@/components/clientProvider";

export const metadata: Metadata = {
  title: "ارز هشت - خرید و فروش ار دیجیتال",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body>
        <ClientProvider>
        {children}
        </ClientProvider>
      </body>
    </html>
  );
}
